package com.hrand.android.timesupmobile.utils

import android.util.Log
import com.hrand.android.timesupmobile.daos.ThemeDao
import com.hrand.android.timesupmobile.daos.WordDao
import com.hrand.android.timesupmobile.models.Theme
import com.hrand.android.timesupmobile.models.Word

fun clearDataBase(){
    Log.d("haja", "clear de la base")
    ThemeDao.clearThemes()
    WordDao.clearWords()
}

fun initThemesData(): MutableList<Theme> {
    val themes = mutableListOf<Theme>()
    val t1 = Theme(value = "Animaux/Insects")
    val t2 = Theme(value = "Villes")
    val t3 = Theme(value = "Célébrités")
    val t4 = Theme(value = "Monuments")
    val t5 = Theme(value = "Sports")
    val t6 = Theme(value = "Jeux Vidéo")
    val t7 = Theme(value = "Cinéma")
    val t8 = Theme(value = "Objets Divers")
    themes.add(t1)
    Log.i("haja", "t1 = ${t1.value}")
    themes.add(t2)
    Log.i("haja", "t2 = ${t2.value}")
    return themes
}

fun initWordsData(): MutableList<Word> {
    val words = mutableListOf<Word>()
    words.addAll(listOf(Word(/*id = 0, */value = "Cheval", difficulty = 1), Word(/*id = 1, */value = "Hypocampe", difficulty = 2), Word(/*id = 2, */value = "Panthere", difficulty = 1), Word(/*id = 3, */value = "Paris", difficulty = 1)))
    return words
}


fun initData(){

    val themes = mutableListOf<Theme>()
    val t1 = Theme(value = "Animaux/Insects")
    val t2 = Theme(value = "Villes")
    val t3 = Theme(value = "Célébrités")
    val t4 = Theme(value = "Monuments")
    val t5 = Theme(value = "Sports")
    val t6 = Theme(value = "Jeux Vidéo")
    val t7 = Theme(value = "Cinéma")
    val t8 = Theme(value = "Objets Divers")
    themes.add(t1)
    themes.add(t2)
    themes.add(t3)
    themes.add(t4)
    themes.add(t5)
    themes.add(t6)
    themes.add(t7)
    themes.add(t8)

    val w1 = Word(value = "Cheval", difficulty = 1)
    w1.themes.add(t1)
    val w2 = Word(value = "Hypocampe", difficulty = 2)
    w2.themes.add(t1)
    val w3 = Word(value = "Panthere", difficulty = 1)
    w3.themes.add(t1)
    val w5 = Word(value = "Lion", difficulty = 1)
    w5.themes.add(t1)
    val w6 = Word(value = "Ours", difficulty = 1)
    w6.themes.add(t1)
    val w7 = Word(value = "Libellule", difficulty = 1)
    w7.themes.add(t1)
    val w8 = Word(value = "Dromadaire", difficulty = 1)
    w8.themes.add(t1)
    val w9 = Word(value = "Léopard", difficulty = 1)
    w9.themes.add(t1)
    val w22 = Word(value = "Libellule", difficulty = 1)
    w22.themes.add(t1)
    val w23 = Word(value = "Singe", difficulty = 1)
    w23.themes.add(t1)
    val w24 = Word(value = "Léopard", difficulty = 1)
    w24.themes.add(t1)

    val w11 = Word(value = "Yoga", difficulty = 1)
    w11.themes.add(t2)
    val w12 = Word(value = "Karaté", difficulty = 1)
    w12.themes.add(t2)

    val w16 = Word(value = "Jackie Chan", difficulty = 1)
    w16.themes.add(t3)
    val w17 = Word(value = "Bruce Lee", difficulty = 2)
    w17.themes.add(t3)
    val w18 = Word(value = "Morgan Freeman", difficulty = 1)
    w18.themes.add(t3)
    val w19 = Word(value = "Joey Tribbiani", difficulty = 1)
    w19.themes.add(t3)
    val w20 = Word(value = "Barney Stinson", difficulty = 1)
    w20.themes.add(t3)
    val w21 = Word(value = "Neymar", difficulty = 1)
    w21.themes.add(t3)

    val w30 = Word(value = "Tour Effel", difficulty = 1)
    w30.themes.add(t4)

    val w4 = Word(value = "Tennis", difficulty = 1)
    w4.themes.add(t5)
    val w13 = Word(value = "Judo", difficulty = 1)
    w13.themes.add(t5)
    val w14 = Word(value = "Baseball", difficulty = 1)
    w14.themes.add(t5)
    val w10 = Word(value = "Pétanque", difficulty = 1)
    w10.themes.add(t5)
    val w25 = Word(value = "Athlétisme", difficulty = 1)
    w25.themes.add(t5)
    val w26 = Word(value = "Yoga", difficulty = 1)
    w26.themes.add(t5)
    val w27 = Word(value = "Karaté", difficulty = 1)
    w27.themes.add(t5)
    val w28 = Word(value = "Badminton", difficulty = 1)
    w28.themes.add(t5)
    val w29 = Word(value = "Crossfit", difficulty = 1)
    w29.themes.add(t5)

    val w15 = Word(value = "Eponge", difficulty = 1)
    w15.themes.add(t8)

    t1.words.add(w1)
    t1.words.add(w2)
    t1.words.add(w3)
    t1.words.add(w5)
    t1.words.add(w6)
    t1.words.add(w7)
    t1.words.add(w8)
    t1.words.add(w9)
    t1.words.add(w22)
    t1.words.add(w23)
    t1.words.add(w24)

    t2.words.add(w11)
    t2.words.add(w12)

    t3.words.add(w16)
    t3.words.add(w17)
    t3.words.add(w18)
    t3.words.add(w20)
    t3.words.add(w21)

    t4.words.add(w30)

    t5.words.add(w4)
    t5.words.add(w10)
    t5.words.add(w13)
    t5.words.add(w14)
    t5.words.add(w25)
    t5.words.add(w26)
    t5.words.add(w27)
    t5.words.add(w28)
    t5.words.add(w29)

    t8.words.add(w15)

    ThemeDao.addThemes(themes)
    WordDao.addWord(w1)
    WordDao.addWord(w2)
    WordDao.addWord(w3)
    WordDao.addWord(w4)
    WordDao.addWord(w5)
    WordDao.addWord(w6)
    WordDao.addWord(w7)
    WordDao.addWord(w8)
    WordDao.addWord(w9)
    WordDao.addWord(w10)
    WordDao.addWord(w11)
    WordDao.addWord(w12)
    WordDao.addWord(w13)
    WordDao.addWord(w14)
    WordDao.addWord(w15)
    WordDao.addWord(w16)
    WordDao.addWord(w17)
    WordDao.addWord(w18)
    WordDao.addWord(w19)
    WordDao.addWord(w20)
    WordDao.addWord(w21)
    WordDao.addWord(w22)
    WordDao.addWord(w23)
    WordDao.addWord(w24)
    WordDao.addWord(w25)
    WordDao.addWord(w26)
    WordDao.addWord(w27)
    WordDao.addWord(w28)
    WordDao.addWord(w29)
    WordDao.addWord(w30)

}
